//! Record layout descriptors batch 7.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_7: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 210,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-07-00",
    },
    LayoutDesc {
        field_id: 211,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-07-01",
    },
    LayoutDesc {
        field_id: 212,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-07-02",
    },
    LayoutDesc {
        field_id: 213,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-07-03",
    },
    LayoutDesc {
        field_id: 214,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-07-04",
    },
    LayoutDesc {
        field_id: 215,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-07-05",
    },
    LayoutDesc {
        field_id: 216,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-07-06",
    },
    LayoutDesc {
        field_id: 217,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-07-07",
    },
    LayoutDesc {
        field_id: 218,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-07-08",
    },
    LayoutDesc {
        field_id: 219,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-07-09",
    },
    LayoutDesc {
        field_id: 220,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-07-10",
    },
    LayoutDesc {
        field_id: 221,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-07-11",
    },
    LayoutDesc {
        field_id: 222,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-07-12",
    },
    LayoutDesc {
        field_id: 223,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-07-13",
    },
    LayoutDesc {
        field_id: 224,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-07-14",
    },
    LayoutDesc {
        field_id: 225,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-07-15",
    },
    LayoutDesc {
        field_id: 226,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-07-16",
    },
    LayoutDesc {
        field_id: 227,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-07-17",
    },
    LayoutDesc {
        field_id: 228,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-07-18",
    },
    LayoutDesc {
        field_id: 229,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-07-19",
    },
    LayoutDesc {
        field_id: 230,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-07-20",
    },
    LayoutDesc {
        field_id: 231,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-07-21",
    },
    LayoutDesc {
        field_id: 232,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-07-22",
    },
    LayoutDesc {
        field_id: 233,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-07-23",
    },
    LayoutDesc {
        field_id: 234,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-07-24",
    },
    LayoutDesc {
        field_id: 235,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-07-25",
    },
    LayoutDesc {
        field_id: 236,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-07-26",
    },
    LayoutDesc {
        field_id: 237,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-07-27",
    },
    LayoutDesc {
        field_id: 238,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-07-28",
    },
    LayoutDesc {
        field_id: 239,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-07-29",
    },
];

pub fn lookup_layout_7(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_7.iter().find(|l| l.field_id == field_id)
}
