//! Record layout descriptors batch 1.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_1: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 30,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-01-00",
    },
    LayoutDesc {
        field_id: 31,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-01-01",
    },
    LayoutDesc {
        field_id: 32,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-01-02",
    },
    LayoutDesc {
        field_id: 33,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-01-03",
    },
    LayoutDesc {
        field_id: 34,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-01-04",
    },
    LayoutDesc {
        field_id: 35,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-01-05",
    },
    LayoutDesc {
        field_id: 36,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-01-06",
    },
    LayoutDesc {
        field_id: 37,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-01-07",
    },
    LayoutDesc {
        field_id: 38,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-01-08",
    },
    LayoutDesc {
        field_id: 39,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-01-09",
    },
    LayoutDesc {
        field_id: 40,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-01-10",
    },
    LayoutDesc {
        field_id: 41,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-01-11",
    },
    LayoutDesc {
        field_id: 42,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-01-12",
    },
    LayoutDesc {
        field_id: 43,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-01-13",
    },
    LayoutDesc {
        field_id: 44,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-01-14",
    },
    LayoutDesc {
        field_id: 45,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-01-15",
    },
    LayoutDesc {
        field_id: 46,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-01-16",
    },
    LayoutDesc {
        field_id: 47,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-01-17",
    },
    LayoutDesc {
        field_id: 48,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-01-18",
    },
    LayoutDesc {
        field_id: 49,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-01-19",
    },
    LayoutDesc {
        field_id: 50,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-01-20",
    },
    LayoutDesc {
        field_id: 51,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-01-21",
    },
    LayoutDesc {
        field_id: 52,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-01-22",
    },
    LayoutDesc {
        field_id: 53,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-01-23",
    },
    LayoutDesc {
        field_id: 54,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-01-24",
    },
    LayoutDesc {
        field_id: 55,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-01-25",
    },
    LayoutDesc {
        field_id: 56,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-01-26",
    },
    LayoutDesc {
        field_id: 57,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-01-27",
    },
    LayoutDesc {
        field_id: 58,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-01-28",
    },
    LayoutDesc {
        field_id: 59,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-01-29",
    },
];

pub fn lookup_layout_1(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_1.iter().find(|l| l.field_id == field_id)
}
