//! Record layout descriptors batch 0.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_0: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 0,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-00-00",
    },
    LayoutDesc {
        field_id: 1,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-00-01",
    },
    LayoutDesc {
        field_id: 2,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-00-02",
    },
    LayoutDesc {
        field_id: 3,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-00-03",
    },
    LayoutDesc {
        field_id: 4,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-00-04",
    },
    LayoutDesc {
        field_id: 5,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-00-05",
    },
    LayoutDesc {
        field_id: 6,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-00-06",
    },
    LayoutDesc {
        field_id: 7,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-00-07",
    },
    LayoutDesc {
        field_id: 8,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-00-08",
    },
    LayoutDesc {
        field_id: 9,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-00-09",
    },
    LayoutDesc {
        field_id: 10,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-00-10",
    },
    LayoutDesc {
        field_id: 11,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-00-11",
    },
    LayoutDesc {
        field_id: 12,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-00-12",
    },
    LayoutDesc {
        field_id: 13,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-00-13",
    },
    LayoutDesc {
        field_id: 14,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-00-14",
    },
    LayoutDesc {
        field_id: 15,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-00-15",
    },
    LayoutDesc {
        field_id: 16,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-00-16",
    },
    LayoutDesc {
        field_id: 17,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-00-17",
    },
    LayoutDesc {
        field_id: 18,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-00-18",
    },
    LayoutDesc {
        field_id: 19,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-00-19",
    },
    LayoutDesc {
        field_id: 20,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-00-20",
    },
    LayoutDesc {
        field_id: 21,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-00-21",
    },
    LayoutDesc {
        field_id: 22,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-00-22",
    },
    LayoutDesc {
        field_id: 23,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-00-23",
    },
    LayoutDesc {
        field_id: 24,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-00-24",
    },
    LayoutDesc {
        field_id: 25,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-00-25",
    },
    LayoutDesc {
        field_id: 26,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-00-26",
    },
    LayoutDesc {
        field_id: 27,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-00-27",
    },
    LayoutDesc {
        field_id: 28,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-00-28",
    },
    LayoutDesc {
        field_id: 29,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-00-29",
    },
];

pub fn lookup_layout_0(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_0.iter().find(|l| l.field_id == field_id)
}
