//! Record layout descriptors batch 6.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_6: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 180,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-06-00",
    },
    LayoutDesc {
        field_id: 181,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-06-01",
    },
    LayoutDesc {
        field_id: 182,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-06-02",
    },
    LayoutDesc {
        field_id: 183,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-06-03",
    },
    LayoutDesc {
        field_id: 184,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-06-04",
    },
    LayoutDesc {
        field_id: 185,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-06-05",
    },
    LayoutDesc {
        field_id: 186,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-06-06",
    },
    LayoutDesc {
        field_id: 187,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-06-07",
    },
    LayoutDesc {
        field_id: 188,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-06-08",
    },
    LayoutDesc {
        field_id: 189,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-06-09",
    },
    LayoutDesc {
        field_id: 190,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-06-10",
    },
    LayoutDesc {
        field_id: 191,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-06-11",
    },
    LayoutDesc {
        field_id: 192,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-06-12",
    },
    LayoutDesc {
        field_id: 193,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-06-13",
    },
    LayoutDesc {
        field_id: 194,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-06-14",
    },
    LayoutDesc {
        field_id: 195,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-06-15",
    },
    LayoutDesc {
        field_id: 196,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-06-16",
    },
    LayoutDesc {
        field_id: 197,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-06-17",
    },
    LayoutDesc {
        field_id: 198,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-06-18",
    },
    LayoutDesc {
        field_id: 199,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-06-19",
    },
    LayoutDesc {
        field_id: 200,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-06-20",
    },
    LayoutDesc {
        field_id: 201,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-06-21",
    },
    LayoutDesc {
        field_id: 202,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-06-22",
    },
    LayoutDesc {
        field_id: 203,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-06-23",
    },
    LayoutDesc {
        field_id: 204,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-06-24",
    },
    LayoutDesc {
        field_id: 205,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-06-25",
    },
    LayoutDesc {
        field_id: 206,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-06-26",
    },
    LayoutDesc {
        field_id: 207,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-06-27",
    },
    LayoutDesc {
        field_id: 208,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-06-28",
    },
    LayoutDesc {
        field_id: 209,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-06-29",
    },
];

pub fn lookup_layout_6(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_6.iter().find(|l| l.field_id == field_id)
}
