//! Record layout descriptors batch 5.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_5: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 150,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-05-00",
    },
    LayoutDesc {
        field_id: 151,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-05-01",
    },
    LayoutDesc {
        field_id: 152,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-05-02",
    },
    LayoutDesc {
        field_id: 153,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-05-03",
    },
    LayoutDesc {
        field_id: 154,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-05-04",
    },
    LayoutDesc {
        field_id: 155,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-05-05",
    },
    LayoutDesc {
        field_id: 156,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-05-06",
    },
    LayoutDesc {
        field_id: 157,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-05-07",
    },
    LayoutDesc {
        field_id: 158,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-05-08",
    },
    LayoutDesc {
        field_id: 159,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-05-09",
    },
    LayoutDesc {
        field_id: 160,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-05-10",
    },
    LayoutDesc {
        field_id: 161,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-05-11",
    },
    LayoutDesc {
        field_id: 162,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-05-12",
    },
    LayoutDesc {
        field_id: 163,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-05-13",
    },
    LayoutDesc {
        field_id: 164,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-05-14",
    },
    LayoutDesc {
        field_id: 165,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-05-15",
    },
    LayoutDesc {
        field_id: 166,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-05-16",
    },
    LayoutDesc {
        field_id: 167,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-05-17",
    },
    LayoutDesc {
        field_id: 168,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-05-18",
    },
    LayoutDesc {
        field_id: 169,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-05-19",
    },
    LayoutDesc {
        field_id: 170,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-05-20",
    },
    LayoutDesc {
        field_id: 171,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-05-21",
    },
    LayoutDesc {
        field_id: 172,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-05-22",
    },
    LayoutDesc {
        field_id: 173,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-05-23",
    },
    LayoutDesc {
        field_id: 174,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-05-24",
    },
    LayoutDesc {
        field_id: 175,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-05-25",
    },
    LayoutDesc {
        field_id: 176,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-05-26",
    },
    LayoutDesc {
        field_id: 177,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-05-27",
    },
    LayoutDesc {
        field_id: 178,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-05-28",
    },
    LayoutDesc {
        field_id: 179,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-05-29",
    },
];

pub fn lookup_layout_5(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_5.iter().find(|l| l.field_id == field_id)
}
