//! Record layout descriptors batch 2.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_2: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 60,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-02-00",
    },
    LayoutDesc {
        field_id: 61,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-02-01",
    },
    LayoutDesc {
        field_id: 62,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-02-02",
    },
    LayoutDesc {
        field_id: 63,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-02-03",
    },
    LayoutDesc {
        field_id: 64,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-02-04",
    },
    LayoutDesc {
        field_id: 65,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-02-05",
    },
    LayoutDesc {
        field_id: 66,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-02-06",
    },
    LayoutDesc {
        field_id: 67,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-02-07",
    },
    LayoutDesc {
        field_id: 68,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-02-08",
    },
    LayoutDesc {
        field_id: 69,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-02-09",
    },
    LayoutDesc {
        field_id: 70,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-02-10",
    },
    LayoutDesc {
        field_id: 71,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-02-11",
    },
    LayoutDesc {
        field_id: 72,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-02-12",
    },
    LayoutDesc {
        field_id: 73,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-02-13",
    },
    LayoutDesc {
        field_id: 74,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-02-14",
    },
    LayoutDesc {
        field_id: 75,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-02-15",
    },
    LayoutDesc {
        field_id: 76,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-02-16",
    },
    LayoutDesc {
        field_id: 77,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-02-17",
    },
    LayoutDesc {
        field_id: 78,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-02-18",
    },
    LayoutDesc {
        field_id: 79,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-02-19",
    },
    LayoutDesc {
        field_id: 80,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-02-20",
    },
    LayoutDesc {
        field_id: 81,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-02-21",
    },
    LayoutDesc {
        field_id: 82,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-02-22",
    },
    LayoutDesc {
        field_id: 83,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-02-23",
    },
    LayoutDesc {
        field_id: 84,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-02-24",
    },
    LayoutDesc {
        field_id: 85,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-02-25",
    },
    LayoutDesc {
        field_id: 86,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-02-26",
    },
    LayoutDesc {
        field_id: 87,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-02-27",
    },
    LayoutDesc {
        field_id: 88,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-02-28",
    },
    LayoutDesc {
        field_id: 89,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-02-29",
    },
];

pub fn lookup_layout_2(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_2.iter().find(|l| l.field_id == field_id)
}
