//! Record layout descriptors batch 4.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_4: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 120,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-04-00",
    },
    LayoutDesc {
        field_id: 121,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-04-01",
    },
    LayoutDesc {
        field_id: 122,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-04-02",
    },
    LayoutDesc {
        field_id: 123,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-04-03",
    },
    LayoutDesc {
        field_id: 124,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-04-04",
    },
    LayoutDesc {
        field_id: 125,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-04-05",
    },
    LayoutDesc {
        field_id: 126,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-04-06",
    },
    LayoutDesc {
        field_id: 127,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-04-07",
    },
    LayoutDesc {
        field_id: 128,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-04-08",
    },
    LayoutDesc {
        field_id: 129,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-04-09",
    },
    LayoutDesc {
        field_id: 130,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-04-10",
    },
    LayoutDesc {
        field_id: 131,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-04-11",
    },
    LayoutDesc {
        field_id: 132,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-04-12",
    },
    LayoutDesc {
        field_id: 133,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-04-13",
    },
    LayoutDesc {
        field_id: 134,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-04-14",
    },
    LayoutDesc {
        field_id: 135,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-04-15",
    },
    LayoutDesc {
        field_id: 136,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-04-16",
    },
    LayoutDesc {
        field_id: 137,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-04-17",
    },
    LayoutDesc {
        field_id: 138,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-04-18",
    },
    LayoutDesc {
        field_id: 139,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-04-19",
    },
    LayoutDesc {
        field_id: 140,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-04-20",
    },
    LayoutDesc {
        field_id: 141,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-04-21",
    },
    LayoutDesc {
        field_id: 142,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-04-22",
    },
    LayoutDesc {
        field_id: 143,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-04-23",
    },
    LayoutDesc {
        field_id: 144,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-04-24",
    },
    LayoutDesc {
        field_id: 145,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-04-25",
    },
    LayoutDesc {
        field_id: 146,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-04-26",
    },
    LayoutDesc {
        field_id: 147,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-04-27",
    },
    LayoutDesc {
        field_id: 148,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-04-28",
    },
    LayoutDesc {
        field_id: 149,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-04-29",
    },
];

pub fn lookup_layout_4(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_4.iter().find(|l| l.field_id == field_id)
}
