//! Record layout descriptors batch 3.

use crate::core::types::RecordKind;

#[derive(Debug, Clone, Copy)]
pub struct LayoutDesc {
    pub field_id: u32,
    pub kind: RecordKind,
    pub offset: u16,
    pub width: u16,
    pub label: &'static str,
}

pub const LAYOUTS_3: &[LayoutDesc] = &[
    LayoutDesc {
        field_id: 90,
        kind: RecordKind::CredentialEntry,
        offset: 0,
        width: 4,
        label: "field-03-00",
    },
    LayoutDesc {
        field_id: 91,
        kind: RecordKind::RotationEvent,
        offset: 4,
        width: 8,
        label: "field-03-01",
    },
    LayoutDesc {
        field_id: 92,
        kind: RecordKind::PolicyBinding,
        offset: 8,
        width: 12,
        label: "field-03-02",
    },
    LayoutDesc {
        field_id: 93,
        kind: RecordKind::DeferredVerify,
        offset: 12,
        width: 16,
        label: "field-03-03",
    },
    LayoutDesc {
        field_id: 94,
        kind: RecordKind::RevocationNotice,
        offset: 16,
        width: 20,
        label: "field-03-04",
    },
    LayoutDesc {
        field_id: 95,
        kind: RecordKind::CredentialEntry,
        offset: 20,
        width: 24,
        label: "field-03-05",
    },
    LayoutDesc {
        field_id: 96,
        kind: RecordKind::RotationEvent,
        offset: 24,
        width: 28,
        label: "field-03-06",
    },
    LayoutDesc {
        field_id: 97,
        kind: RecordKind::PolicyBinding,
        offset: 28,
        width: 32,
        label: "field-03-07",
    },
    LayoutDesc {
        field_id: 98,
        kind: RecordKind::DeferredVerify,
        offset: 32,
        width: 4,
        label: "field-03-08",
    },
    LayoutDesc {
        field_id: 99,
        kind: RecordKind::RevocationNotice,
        offset: 36,
        width: 8,
        label: "field-03-09",
    },
    LayoutDesc {
        field_id: 100,
        kind: RecordKind::CredentialEntry,
        offset: 40,
        width: 12,
        label: "field-03-10",
    },
    LayoutDesc {
        field_id: 101,
        kind: RecordKind::RotationEvent,
        offset: 44,
        width: 16,
        label: "field-03-11",
    },
    LayoutDesc {
        field_id: 102,
        kind: RecordKind::PolicyBinding,
        offset: 48,
        width: 20,
        label: "field-03-12",
    },
    LayoutDesc {
        field_id: 103,
        kind: RecordKind::DeferredVerify,
        offset: 52,
        width: 24,
        label: "field-03-13",
    },
    LayoutDesc {
        field_id: 104,
        kind: RecordKind::RevocationNotice,
        offset: 56,
        width: 28,
        label: "field-03-14",
    },
    LayoutDesc {
        field_id: 105,
        kind: RecordKind::CredentialEntry,
        offset: 60,
        width: 32,
        label: "field-03-15",
    },
    LayoutDesc {
        field_id: 106,
        kind: RecordKind::RotationEvent,
        offset: 64,
        width: 4,
        label: "field-03-16",
    },
    LayoutDesc {
        field_id: 107,
        kind: RecordKind::PolicyBinding,
        offset: 68,
        width: 8,
        label: "field-03-17",
    },
    LayoutDesc {
        field_id: 108,
        kind: RecordKind::DeferredVerify,
        offset: 72,
        width: 12,
        label: "field-03-18",
    },
    LayoutDesc {
        field_id: 109,
        kind: RecordKind::RevocationNotice,
        offset: 76,
        width: 16,
        label: "field-03-19",
    },
    LayoutDesc {
        field_id: 110,
        kind: RecordKind::CredentialEntry,
        offset: 80,
        width: 20,
        label: "field-03-20",
    },
    LayoutDesc {
        field_id: 111,
        kind: RecordKind::RotationEvent,
        offset: 84,
        width: 24,
        label: "field-03-21",
    },
    LayoutDesc {
        field_id: 112,
        kind: RecordKind::PolicyBinding,
        offset: 88,
        width: 28,
        label: "field-03-22",
    },
    LayoutDesc {
        field_id: 113,
        kind: RecordKind::DeferredVerify,
        offset: 92,
        width: 32,
        label: "field-03-23",
    },
    LayoutDesc {
        field_id: 114,
        kind: RecordKind::RevocationNotice,
        offset: 96,
        width: 4,
        label: "field-03-24",
    },
    LayoutDesc {
        field_id: 115,
        kind: RecordKind::CredentialEntry,
        offset: 100,
        width: 8,
        label: "field-03-25",
    },
    LayoutDesc {
        field_id: 116,
        kind: RecordKind::RotationEvent,
        offset: 104,
        width: 12,
        label: "field-03-26",
    },
    LayoutDesc {
        field_id: 117,
        kind: RecordKind::PolicyBinding,
        offset: 108,
        width: 16,
        label: "field-03-27",
    },
    LayoutDesc {
        field_id: 118,
        kind: RecordKind::DeferredVerify,
        offset: 112,
        width: 20,
        label: "field-03-28",
    },
    LayoutDesc {
        field_id: 119,
        kind: RecordKind::RevocationNotice,
        offset: 116,
        width: 24,
        label: "field-03-29",
    },
];

pub fn lookup_layout_3(field_id: u32) -> Option<&'static LayoutDesc> {
    LAYOUTS_3.iter().find(|l| l.field_id == field_id)
}
